### PR TITLE
Update graph.py

### PR DESCRIPTION
**Pull request by AnujSaha0111**

### CODE REVIEW

**Comment by this-is-yaash** [comment]
What changes did you made exactly?

It doesn't show me any changes you've made?

**Comment by AnujSaha0111** [comment]
Removed the comments and made PR as you have said earlier

**Comment by this-is-yaash** [comment]
Yeah, but there's no changes is showing up.
It should atleast show that updates you made for iOS support, but there isn't any!

**Comment by AnujSaha0111** [comment]
again sent the new PR

**Pull request closed without merging**
