### PR TITLE
Update graph.py

### PR DESCRIPTION
**Pull request by AnujSaha0111**
Added support for iOS using pbcopy in graph.py

### CODE REVIEW

**Comment by this-is-yaash** [comment]
@AnujSaha0111 great!
You just have to resolve 3 pending requests, then you'll be good to go.

**Comment by AnujSaha0111** [comment]
Was it merged successfully?

**Comment by this-is-yaash** [comment]
No, you should make 3 changes.
Then you are good to get your PR merged!

**Comment by AnujSaha0111** [comment]
What 3 changes?

**Comment by this-is-yaash** [comment]
> What 3 changes?

Look at this PR comments!

**Comment by AnujSaha0111** [comment]
I have committed changes, but it is not reflecting.
this following is updated:

import os
import subprocess
import sys


def display(snippet_name):
    """
    Displays the contents of a Python code snippet file and copies the source code 
    to the clipboard based on the operating system.

    Parameters:
    snippet_name (str): The name of the code snippet file (without .py extension) 
                        to display and copy.

    Raises:
    OSError: If the operating system is unsupported for copying to the clipboard.
    """
    snippet_path = os.path.join(
        os.path.dirname(__file__), "code_snippets", f"{snippet_name}.py"
    )

    with open(snippet_path, "r") as file:
        source_code = file.read()

    def copy_to_clipboard(text):
        """
        Copies the provided text to the clipboard based on the operating system.

        Parameters:
        text (str): The text to copy to the clipboard.

        Raises:
        OSError: If the operating system is unsupported for copying to the clipboard.
        """
        if "linux" in sys.platform:
            subprocess.run(
                ["/usr/bin/xclip", "-selection", "clipboard"],
                input=text.strip().encode(),
                check=True,
            )
        elif "win32" in sys.platform:
            subprocess.run(
                ["C:\\Windows\\System32\\clip.exe"],
                input=text.strip().encode(),
                check=True,
            )
        elif "darwin" in sys.platform:
            subprocess.run(
                ["/usr/bin/pbcopy"],  # Full path to pbcopy for macOS
                input=text.strip().encode(),
                check=True,
            )
        else:
            raise OSError("Unsupported operating system")

    print(source_code)
    copy_to_clipboard(source_code)

**Comment by this-is-yaash** [comment]
image
image


these are the 2 changes I have requested

**Comment by this-is-yaash** [comment]
Scroll up the PR comments 
and look into the comment I've made in your changes

**Comment by AnujSaha0111** [comment]
made the changes. If it is not showing to you, here is the code:


```
import os
import subprocess
import sys


def display(snippet_name):
    snippet_path = os.path.join(
        os.path.dirname(__file__), "code_snippets", f"{snippet_name}.py"
    )

    with open(snippet_path, "r") as file:
        source_code = file.read()

    def copy_to_clipboard(text):
        if "linux" in sys.platform:
            subprocess.run(
                ["/usr/bin/xclip", "-selection", "clipboard"],
                input=text.strip().encode(),
                check=True,
            )
        elif "win32" in sys.platform:
            subprocess.run(
                ["C:\\Windows\\System32\\clip.exe"],
                input=text.strip().encode(),
                check=True,
            )
        elif "darwin" in sys.platform:
            subprocess.run(
                ["/usr/bin/pbcopy"],  # Full path to pbcopy for macOS
                input=text.strip().encode(),
                check=True,
            )
        else:
            raise OSError("Unsupported operating system")

    # The following lines have been removed:
    # print(source_code)
    # copy_to_clipboard(source_code)
```

**Comment by this-is-yaash** [comment]
You should **commit&push**, then only it will reflect the changes on github!

**Comment by AnujSaha0111** [comment]
I have done already.

**Comment by this-is-yaash** [comment]
Also, remove the last 3 lines.  
I don’t want them to be uncommented but removed instead!

**Comment by AnujSaha0111** [comment]
Done👍

**Comment by this-is-yaash** [comment]
image
see this commit section, it only has the commit you've made 1 hour ago!
i.e, it only has 1 commit, which were made 1 hour ago. I want you to commit the new changes.

**Comment by AnujSaha0111** [comment]
image
image
image
I have updated them

Code:  

```
import os
import subprocess
import sys


def display(snippet_name):
    snippet_path = os.path.join(
        os.path.dirname(__file__), "code_snippets", f"{snippet_name}.py"
    )

    with open(snippet_path, "r") as file:
        source_code = file.read()

    def copy_to_clipboard(text):
        if "linux" in sys.platform:
            subprocess.run(
                ["/usr/bin/xclip", "-selection", "clipboard"],
                input=text.strip().encode(),
                check=True,
            )
        elif "win32" in sys.platform:
            subprocess.run(
                ["C:\\Windows\\System32\\clip.exe"],
                input=text.strip().encode(),
                check=True,
            )
        elif "darwin" in sys.platform:
            subprocess.run(
                ["/usr/bin/pbcopy"],  # Full path to pbcopy for macOS
                input=text.strip().encode(),
                check=True,
            )
        else:
            raise OSError("Unsupported operating system")

```

**Comment by this-is-yaash** [comment]
it was committed on you `new-updated-PR` branch.
make sure you send req from that branch!

This PR is under `new-pull-request` branch, so it won't show the changes

Go the `new-updated-PR` and send PR from that branch itself!

**Comment by AnujSaha0111** [comment]
Made changes into new pull request branch

**Comment by AnujSaha0111** [comment]
Sorry Sir....
Again and again new branches and new PR somewhat confused me...
I have just started open source contributing

**Review by this-is-yaash — APPROVED** [review]

**Comment by this-is-yaash** [comment]
It was all good, but you should pull changes from the main branch.
your branch used old naming conventions of directories.

please do git pull and send PR

**Comment by this-is-yaash** [comment]
your forked repository and the main branch are not updated!

**Comment by AnujSaha0111** [comment]
Now, will I update them in main branch?

**Comment by this-is-yaash** [comment]
> Sorry Sir.... Again and again new branches and new PR somewhat confused me... I have just started open source contributing

No problem, this was all a learning phase in your beginner's journey!

**Comment by AnujSaha0111** [comment]
in the fork repository, I have updated in the main branch

**Comment by this-is-yaash** [comment]
> Now, will I update them in main branch?

no, you should pull changes from the main branch (i.e this repo) to you forked repo
commit again and make PR

**Comment by this-is-yaash** [comment]
image

did you see this, 
`matplotlib_visual` but the current repository has renamed it to `pacakge`.
You create new branch from your main branch of the forker repo and work on the issue again!

Make sure forked branch and main branch are identical

**Comment by AnujSaha0111** [comment]
sent a new PR to you

**Pull request closed without merging**
