### PR TITLE
Update graph.py

### PR DESCRIPTION
**Pull request by AnujSaha0111**
I have sent this new PR, since there were some problem from previous PR

### CODE REVIEW

**Comment by this-is-yaash** [comment]
Complete the 3 requests
then we'll merge your PR

**Comment by AnujSaha0111** [comment]
image
no comments are showing

**Comment by this-is-yaash** [comment]
Look at the `Conversation` section, not `File Changes`

**Comment by AnujSaha0111** [comment]
image
image

where Sir in conversation?

**Review by this-is-yaash — COMMENTED** [review]
I hope the required changes are visible for you!
please make the necessary updates and let me know

**Comment by AnujSaha0111** [comment]
Done with them

**Review by this-is-yaash — APPROVED** [review]
LGTM!

**Review by jindalpriyanshu101 — APPROVED** [review]
LGTM!

**Review by Wahid7852 — APPROVED** [review]
LGTM!

**Pull request merged**
