### PR TITLE
Update graph.py

### PR DESCRIPTION
**Pull request by AnujSaha0111**
Coorecting the matplotlib_visual /graph.py - Code Snippet Display Function Issue

### CODE REVIEW

**Review by AnujSaha0111 — COMMENTED** [review]
Updated graph.py file with the issue corrected

**Comment by this-is-yaash** [comment]
Hey @AnujSaha0111 thanks for showing interest in contributing this project!
If you are contributing under **GSSOC**, please either raise an issue or make a comment on an existing to work on it.

Don't make PRs(Pull Requests) on your own. I'll merge them, but you won't get your score 🙃. GSSoC only counts issues and PRs that are properly mapped with the **GSSoC label**.


Let me know if you'd like me to create an issue for you, or you can create your own, and I'll assign it to you after reviewing it!

**Comment by AnujSaha0111** [comment]
Can you assign me the same issue, since after solving this issue only, I can solve the password issue

**Comment by this-is-yaash** [comment]
Okay, I'll create a new issue and assign it to you!

**Pull request closed without merging**
